config/routes.rb
Rails.application.routes.draw do
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # vote comments
  #  resources :vote_comments

  # vote publications
  post 'votes', to: 'votes#add_vote'
  post 'vote_comments', to: 'vote_comments#add_vote', as: 'add_comment_vote'

  # moderators
  post 'moderate/request', to: 'requests#apply'
  patch 'moderate/request/:id', to: 'requests#accept'
  delete 'moderate/request/:id', to: 'requests#reject'
  get 'moderate/request', to: 'requests#show', as: 'requests'
  delete 'moderate', to: 'requests#resign'

  # resources
  resources :publications
  resources :comments
  resources :subscriptions
  resources :favorites
  resources :forums

  # polls
  post 'poll', to: 'publications#poll_vote', as: 'poll_vote'

  # users
  resources :users
  post '/upload/:id', to: 'users#upload'

  # forums
  get '/forums/:id/new_publication/text', to: 'forums#new_publication', as: 'new_publication_text'
  get '/forums/:id/new_publication/link', to: 'forums#new_publication_link', as: 'new_publication_link'
  get '/forums/:id/new_publication/image', to: 'forums#new_publication_image', as: 'new_publication_image'
  post '/forums/:id/new_publication/image', to: 'forums#image_upload', as: 'image_upload'
  get '/forums/:id/new_publication/poll', to: 'forums#new_publication_poll', as: 'new_publication_poll'
  post '/forums/:id/new_publication/poll', to: 'forums#create_poll', as: 'create_poll'
  post '/forums/:id/new_publication/link', to: 'forums#create_link', as: 'create_link'

  # search
  get '/home/search/forums', to: 'home#search_forum', as: 'search_forum'
  get '/home/search/publications', to: 'home#search_publication', as: 'search_publication'
  get '/home/search/users', to: 'home#search_user', as: 'search_user'

  #  top
  get '/home/top_forums', to: 'home#top_forums', as: 'top_forums'
  get '/home/top/publications', to: 'home#top_publications', as: 'top_publications'
  get '/home/top/users', to: 'home#top_users', as: 'top_users'
  get '/home/top/subscribed', to: 'home#top_subscribed', as: 'top_subscribed'

  # home and root
  get 'welcome/index'
  root 'welcome#index'
  get '/home', to: 'home#index', as: :home

  # dashboard
  get '/stats', to: 'statistics#index', as: '/stats'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :vote_comments, dependent: :destroy
  before_create :default_votos

  def default_votos
    self.votos = 0
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments
  # POST /comments.json
  def create
    current_user.reputation += 1
    if comment_params[:commentable_type] == 'publication'
      publication = Publication.find(comment_params[:commentable_id])
      redirect_to publication, notice: 'Comment added' if publication.comments.create(comment_params)
    elsif comment_params[:commentable_type] == 'comment'
      comment = Comment.find(comment_params[:commentable_id])
      root = comment
      root = root.commentable while root.commentable_type != 'Publication'
      publication = root.commentable
      redirect_to publication, notice: 'Comment added' if comment.comments.create(comment_params)
    end
    update_votes(publication)
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html do
          redirect_to @comment, notice: 'Comment was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json do
          render json: @comment.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    root = @comment
    root = root.commentable while root.commentable_type != 'Publication'
    publication = root.commentable
    @comment.destroy
    respond_to do |format|
      format.html do
        redirect_to publication, notice: 'Comment was successfully deleted.'
      end
      format.json { head :no_content }
    end
  end

  private

  def update_votes(publication)
    publication.votos += 1
    publication.forum.votos += 1
    publication.save
    publication.forum.save
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:content, :user_id, :commentable_id, :commentable_type)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% if user_signed_in? %>
<li class="">
  <div class="row">
    <div class="col-xs-1 publication-score">
      <div class="row arrows">
        <% vote = VoteComment.where(user_id: current_user.id, comment_id: comment.id).to_a %>

        <% vote = if vote.empty? %>
        <%         VoteComment.new %>
        <%         else %>
        <%         vote[0] %>
        <%         end %>
        <%= form_for vote, url: add_comment_vote_path, method: :post do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id  %>
        <%= f.hidden_field :comment_id, value: comment.id  %>
        <%= f.hidden_field :positive, value: true  %>
        <button
          type="submit"
          class="submit-icon-green <%= vote.new_record? ?  '' : vote.positive ? 'green' : ''  %>"
          <%= vote.new_record? ?  '' : vote.positive ? 'disabled' : ''  %>>
          <span class="glyphicon glyphicon-chevron-up"></span>
        </button>
        <% end %>
      </div>
      <div class="row arrows">
        <p>
          <strong><%= comment.votos %> </strong>
        </p>
      </div>
      <div class="row arrows">
        <%= form_for vote, url: add_comment_vote_path, method: :post do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id  %>
        <%= f.hidden_field :comment_id, value: comment.id  %>
        <%= f.hidden_field :positive, value: false  %>
        <button
          type="submit"
          class="submit-icon-red <%= vote.new_record? ?  '' : vote.positive ? '' : 'red'  %>"
          <%= vote.new_record? ?  '' : vote.positive ? '' : 'disabled'  %>>
          <span class="glyphicon glyphicon-chevron-down"></span>
        </button>
        <% end %>
      </div>
    </div>
    <div class="col-xs-11">
      <div class="comment-box">
        <div class="comment-small">
          <%= link_to comment.user.userName, comment.user %> ·
          <% hours = (((@time - comment.created_at) / 3600).to_i) %>
          <% if  hours.zero? %>
          Just now
          <% elsif  hours < 24 %>
          <%= hours %> hours ago
          <% else %>
          <%= (hours / 24).to_i%> days ago
          <% end %>
        </div>
        <p> <%= comment.content %> </p>
        <div class="comment-small">
          <% if (user_signed_in?) %>
          <% if check_credentials current_user, @publication %>
          <%= link_to 'Delete', comment, method: :delete %>
          <% end %>
          <% end %>
          <a class="reply-link" id="<%= comment.id %>" >Reply</a>
        </div>
        <div id="comment-<%= comment.id %>" class="hide reply-form">
          <%= form_for Comment.new do |f| %>
          <%= f.text_field :content  %>
          <%= f.hidden_field :user_id, value: current_user.id  %>
          <%= f.hidden_field :commentable_type, value: 'comment'  %>
          <%= f.hidden_field :commentable_id, value: comment.id  %>
          <%= f.submit class: 'btn btn-default'%>
          <% end %>
        </div>
      </div>
      <ul class="comment-list">
          <%= render partial: 'comments/comment', collection: comment.comments.order(:created_at) %>
      </ul>
    </div>

  </div>

</li>

<% else %>

<li class="">
  <div class="row">
    <div class="col-xs-1 publication-score">
      <div class="row arrows">
        <p>
          <strong><%= comment.votos %> </strong>
        </p>
      </div>
    </div>
    <div class="col-xs-11">
      <div class="comment-box">
        <div class="comment-small">
          <%= link_to comment.user.userName, comment.user %> ·
          <% hours = (((@time - comment.created_at) / 3600).to_i) %>
          <% if  hours.zero? %>
          Just now
          <% elsif  hours < 24 %>
          <%= hours %> hours ago
          <% else %>
          <%= (hours / 24).to_i%> days ago
          <% end %>
        </div>
        <p> <%= comment.content %> </p>
        <div class="comment-small">
          <% if (user_signed_in?) %>
          <% if check_credentials current_user, @publication %>
          <%= link_to 'Delete', comment, method: :delete %>
          <% end %>
          <% end %>
        </div>
      </div>
      <ul class="comment-list">
          <%= render partial: 'comments/comment', collection: comment.comments.order(:created_at) %>
      </ul>
    </div>

  </div>



</li>

<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :comment_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :comment_user_id %>
  </div>

  <div class="field">
    <%= form.label :publication_id %>
    <%= form.text_field :publication_id, id: :comment_publication_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% if user_signed_in? && current_user.role.zero? %>
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |

<% else %>

<h2><strong> We're Sorry! </strong></h2>
<p style="font-size:20px"> You don't have permission to access this page. </p>

<% end %>

<%= link_to 'Back to Home', :home %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Publication</th>
      <% if user_signed_in? && current_user.role.zero? %>
      <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= link_to comment.user.userName, comment.user %></td>
        <td><%= link_to comment.publication.title, comment.publication %></td>
        <% if user_signed_in? && current_user.role.zero? %>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<% if user_signed_in? && current_user.role.zero? %>
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<% else %>

<h2><strong> We're Sorry! </strong></h2>
<p style="font-size:20px"> You don't have permission to access this page. </p>

<% end %>

<%= link_to 'Back to Home', :home %>