config/routes.rb
Rails.application.routes.draw do
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # vote comments
  #  resources :vote_comments

  # vote publications
  post 'votes', to: 'votes#add_vote'
  post 'vote_comments', to: 'vote_comments#add_vote', as: 'add_comment_vote'

  # moderators
  post 'moderate/request', to: 'requests#apply'
  patch 'moderate/request/:id', to: 'requests#accept'
  delete 'moderate/request/:id', to: 'requests#reject'
  get 'moderate/request', to: 'requests#show', as: 'requests'
  delete 'moderate', to: 'requests#resign'

  # resources
  resources :publications
  resources :comments
  resources :subscriptions
  resources :favorites
  resources :forums

  # polls
  post 'poll', to: 'publications#poll_vote', as: 'poll_vote'

  # users
  resources :users
  post '/upload/:id', to: 'users#upload'

  # forums
  get '/forums/:id/new_publication/text', to: 'forums#new_publication', as: 'new_publication_text'
  get '/forums/:id/new_publication/link', to: 'forums#new_publication_link', as: 'new_publication_link'
  get '/forums/:id/new_publication/image', to: 'forums#new_publication_image', as: 'new_publication_image'
  post '/forums/:id/new_publication/image', to: 'forums#image_upload', as: 'image_upload'
  get '/forums/:id/new_publication/poll', to: 'forums#new_publication_poll', as: 'new_publication_poll'
  post '/forums/:id/new_publication/poll', to: 'forums#create_poll', as: 'create_poll'
  post '/forums/:id/new_publication/link', to: 'forums#create_link', as: 'create_link'

  # search
  get '/home/search/forums', to: 'home#search_forum', as: 'search_forum'
  get '/home/search/publications', to: 'home#search_publication', as: 'search_publication'
  get '/home/search/users', to: 'home#search_user', as: 'search_user'

  #  top
  get '/home/top_forums', to: 'home#top_forums', as: 'top_forums'
  get '/home/top/publications', to: 'home#top_publications', as: 'top_publications'
  get '/home/top/users', to: 'home#top_users', as: 'top_users'
  get '/home/top/subscribed', to: 'home#top_subscribed', as: 'top_subscribed'

  # home and root
  get 'welcome/index'
  root 'welcome#index'
  get '/home', to: 'home#index', as: :home

  # dashboard
  get '/stats', to: 'statistics#index', as: '/stats'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  belongs_to :forum
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_one :poll, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_create :default_votos

  def default_votos
    self.votos = 0
  end

  def self.search(search)
    where('title ILIKE ? OR content ILIKE ?', "%#{search}%", "%#{search}%")
  end
end

app/controllers/publications_controller.rb
# frozen_string_literal: true

class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[show edit update destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    subscriptors = Subscription.where(forum: @publication.forum).count
    @publication.forum.subscriptors = subscriptors
    if @publication.content_type == 'poll'
      poll = @publication.poll
      poll.total = 0
      poll.poll_options.each do |option|
        poll.total += option.votos
      end
    end
    @time = Time.zone.now
    if user_signed_in?
      @comment = Comment.new
      vote = Vote.where(user_id: current_user.id,
                        publication_id: @publication.id).to_a
      @vote = if vote.empty?
                Vote.new
              else
                vote[0]
              end
      @vote_comment = VoteComment.new
      current = Favorite.where(publication: @publication, user: current_user).take
      @favorite = if current.nil?
                    Favorite.new
                  else
                    current
                  end
    end
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit; end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.votos = 0
    @publication.forum.votos += 1
    respond_to do |format|
      current_user.reputation += 1
      if @publication.save && current_user.save && @publication.forum.save
        format.html do
          redirect_to @publication, \
                      notice: 'Publication was successfully created.'
        end
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json do
          render json: @publication.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html do
          redirect_to @publication,\
                      notice: 'Publication was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json do
          render json: @publication.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    forum = @publication.forum
    @publication.destroy
    respond_to do |format|
      format.html do
        redirect_to forum,\
                    notice: 'Publication was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def poll_vote
    poll = Poll.find(params[:poll_id])
    option = PollOption.find(params[:vote])
    option.votos += 1
    option.save
    vote = PollVote.new(poll: poll, poll_option: option, user: current_user)
    vote.save
    redirect_to poll.publication
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_publication
    @publication = Publication.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def publication_params
    params.require(:publication).permit(:title, :content, :user_id, :forum_id)
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
  def check_credentials(user, publication)
    if user.role.zero?
      return true
    elsif user.moderated_forums.include?(publication.forum)
      return true
    elsif publication.user == user
      return true
    end
    false
  end
end

app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true) do |form| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>
      <ul>
      <% publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :publication_title, required: true %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :publication_content, required: true %>
  </div>
  <% if @publication.new_record? %>
    <%= form.hidden_field :user_id, id: :publication_user_id, value: current_user.id %>
    <%= form.hidden_field :forum_id, id: :publication_forum_id, value: @forum_id %>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_form_image.html.erb
<%= form_tag(image_upload_path, multipart: true) do %>
  <%= label_tag :title %>
  <%= text_field_tag :title, '', id: :publication_title, required: true%>
  <%= label_tag :content %>
  <%= text_area_tag :content, '', id: :publication_content, required: true %>
  <%= file_field_tag :picture, required: true %>
  <%= submit_tag 'Submit' %>
<% end %>

app/views/publications/_form_link.html.erb
<%= form_tag create_link_path, method: :post %>
<%= label_tag :publication_title, 'Publication Title:' %>
<%= text_field_tag :publication_title,'', required: true %><br>
<%= label_tag :url, 'Url:' %>
<%= url_field_tag :url, '', required: true %><br>
<%= submit_tag 'Submit' %>

app/views/publications/_form_poll.html.erb
<%= form_tag create_poll_path, method: :post %>
<%= label_tag :publication_title, 'Publication Title:' %>
<%= text_field_tag :publication_title, '',required: true %><br>
<%= label_tag :question, 'Poll:' %>
<%= text_field_tag :question, '',required: true %><br>
<%= label_tag :option_1, 'Option 1:' %>
<%= text_field_tag :option_1, '',required: true %><br>
<%= label_tag :option_2, 'Option 2:' %>
<%= text_field_tag :option_2, '',required: true %><br>
<%= label_tag :option_3, 'Option 3:' %>
<%= text_field_tag :option_3 %><br>
<%= label_tag :option_4, 'Option 4:' %>
<%= text_field_tag :option_4 %><br>
<%= submit_tag 'Submit' %>

app/views/publications/edit.html.erb
<% if user_signed_in? %>
<br>
<h1>Editing <%=@publication.content_type %>  publication</h1>

	<%= render 'form', publication: @publication %>
	
	<%= link_to 'Show', @publication %> |

<% else %>

<h2><strong> We're Sorry! </strong></h2>
<p style="font-size:20px"> You don't have permission to access this page. </p>

<% end %>

<%= link_to 'Back', @publication %>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Publications</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>Forum</th>
    </tr>
  </thead>

  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= link_to publication.title, publication %></td>
        <td><%= publication.content %></td>
        <%puts(publication) %>
        <td><%= link_to publication.user.userName, publication.user  %></td>
        <td><%= link_to publication.forum.title, publication.forum  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back to Home', :home %>

app/views/publications/new.html.erb
<% if user_signed_in? %>

<h1>New Publication</h1>

<%= render 'publications/form', publication: @publication %>

<% else %>

<h2><strong> We're Sorry! </strong></h2>
<p style="font-size:20px"> You don't have permission to access this page. </p>

<% end %>


<%= link_to 'Back to Home', '/home' %>

app/views/publications/new_image.html.erb
<% if user_signed_in? %>

<h1>New Publication</h1>

<%= render 'publications/form_image', publication: @publication %>

<% else %>

<h2><strong> We're Sorry! </strong></h2>
<p style="font-size:20px"> You don't have permission to access this page. </p>

<% end %>


<%= link_to 'Back to Home', '/home' %>

app/views/publications/new_link.html.erb
<% if user_signed_in? %>

<h1>New Publication</h1>

<%= render 'publications/form_link', publication: @publication%>

<% else %>

<h2><strong> We're Sorry! </strong></h2>
<p style="font-size:20px"> You don't have permission to access this page. </p>

<% end %>


<%= link_to 'Back to Home', '/home' %>

app/views/publications/new_poll.html.erb
<% if user_signed_in? %>

<h1>New Publication</h1>

<%= render 'publications/form_poll', publication: @publication, poll: @poll %>

<% else %>

<h2><strong> We're Sorry! </strong></h2>
<p style="font-size:20px"> You don't have permission to access this page. </p>

<% end %>


<%= link_to 'Back to Home', '/home' %>

app/views/publications/show.html.erb
<% provide(:title, @publication.title) %>
<% if user_signed_in? %>
  <div class="row publication-meta">
      <p>
        Created by
        <%= link_to @publication.user.userName, @publication.user %>
        <% hours = (((Time.zone.now - @publication.created_at) / 3600).to_i) %>
        <% if  hours.zero? %>
        just now
        <% elsif  hours < 24 %>
        <%= hours %> hours ago
        <% else %>
        <%= (hours / 24).to_i%> days ago
        <% end %>
      </p>
  </div>
  <div class="row">
    <div class="col-xs-9">
      <div class="row">
        <div class="col-xs-1 publication-score">
          <div class="row arrows">
            <%= form_for @vote, url: votes_path, method: :post do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id  %>
            <%= f.hidden_field :publication_id, value: @publication.id  %>
            <%= f.hidden_field :positive, value: true  %>
            <button
              type="submit"
              class="submit-icon-green <%= @vote.new_record? ?  '' : @vote.positive ? 'green' : ''  %>"
              <%= @vote.new_record? ?  '' : @vote.positive ? 'disabled' : ''  %>>
              <span class="glyphicon glyphicon-chevron-up"></span>
            </button>
            <% end %>
          </div>
          <div class="row arrows">
            <p>
              <strong><%=@publication.votos%></strong>
            </p>
          </div>
          <div class="row arrows">
            <%= form_for @vote, url: votes_path, method: :post do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id  %>
            <%= f.hidden_field :publication_id, value: @publication.id  %>
            <%= f.hidden_field :positive, value: false  %>
            <button
              type="submit"
              class="submit-icon-red <%= @vote.new_record? ?  '' : @vote.positive ? '' : 'red'  %>"
              <%= @vote.new_record? ?  '' : @vote.positive ? '' : 'disabled'  %>>
              <span class="glyphicon glyphicon-chevron-down"></span>
            </button>
            <% end %>
          </div>
          <div class="row arrows">
            <% if current_user.favorite_publications.include?(@publication) %>
              <%= form_for @favorite, method: :delete do |f| %>
              <%= f.hidden_field :publication_id, value: @publication.id  %>
              <%= f.hidden_field :user_id, value: current_user.id  %>
              <button type="submit" class="submit-icon-full">
                <span class="glyphicon glyphicon-star"></span>
              </button>
              <% end  %>
            <% else %>
              <%= form_for @favorite do |f| %>
              <%= f.hidden_field :publication_id, value: @publication.id  %>
              <%= f.hidden_field :user_id, value: current_user.id  %>
              <button type="submit" class="submit-icon-empty">
                <span class="glyphicon glyphicon-star-empty"></span>
              </button>
              <% end  %>
            <% end  %>
          </div>
        </div>
        <div class="col-xs-11">
          <h1 id="publication-title">
            <strong><%= @publication.title %> </strong>
          </h1>
          <% if @publication.content_type == 'link' %>
            <a href="<%= @publication.content %> "><%= @publication.content %> </a>
          <% else %>
          <p style="font-size:110%;">
            <%= @publication.content %>
          </p>
          <% end %>
          <% if @publication.content_type == 'poll' %>
            <div class="poll-container">
              <h3><%= @publication.poll.question %> </h3>
              <%if PollVote.where(user_id: current_user.id, poll_id: @publication.poll.id).to_a.empty? %>
                <%= form_tag poll_vote_path do  %>
                <%= hidden_field_tag :poll_id, @publication.poll.id %>
                  <% @publication.poll.poll_options.each do |option| %>
                  <% unless option.text == "" %>
                    <button type="submit" name="vote" class="btn btn-default" value="<%= option.id %>"><%= option.text %> </button><br>
                  <% end %>
                  <% end %>
                <% end %>
              <% else %>
                <% @publication.poll.poll_options.each do |option| %>
                <% unless option.text == "" %>
                <% value = (option.votos*100/@publication.poll.total).to_i %>
                <div class="progress">
                  <div class="progress-bar" style="width: <%=value %>%;" role="progressbar" aria-valuenow="<%= value %>" aria-valuemin="0" aria-valuemax="100">
                    <span><%= option.text %></span>
                    <span class="percent"><%= value %>% </span>
                  </div>
                </div>
                <% end %>
                <% end %>
              <% end %>
            </div>

          <% end %>
          <% unless @publication.image.nil? %>
          <img src="<%= @publication.image %> " alt="" width=100%; >
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <h3>Comment Section</h3>
          <ul class="comment-list">
            <%= render partial: 'comments/comment', collection: @publication.comments.order(:created_at) %>
          </ul>
          <% if (user_signed_in?) %>
            <%= form_for @comment do |f| %>
            <%= f.text_field :content  %>
            <%= f.hidden_field :user_id, value: current_user.id  %>
            <%= f.hidden_field :commentable_type, value: 'publication'  %>
            <%= f.hidden_field :commentable_id, value: @publication.id  %>
            <%= f.submit class: 'btn btn-default'%>
            <% end %>
          <% end %>

        <% if user_signed_in? %>
          <% if @publication.user == current_user %>
            <%= link_to 'Edit', edit_publication_path(@publication) %> |
          <% end %>
          <% if check_credentials current_user, @publication %>
          <%= link_to 'Destroy', @publication, method: :delete, data: { confirm: 'Are you sure?' } %> |
          <% end %>
        <% end %>
        <%= link_to 'Back', @publication.forum %>
        </div>
      </div>
    </div>
    <div class="col-xs-3 publication-sidebar">
      <div class="sidebar-container">
        <div class="sidebar-topbar"></div>
        <div class="sidebar-content">
          <h3>
            <%= link_to @publication.forum.title, @publication.forum %>
          </h3>
          <p><strong><%= @publication.forum.subscriptors %> Subscribers</strong> </p>
          <p><%= @publication.forum.description %> </p>
          <% if  user_signed_in? %>
            <% current = Subscription.where(forum: @publication.forum, user: current_user).take %>
            <% subscription = current.nil? ? Subscription.new : current %>
            <% if current_user.forums.include?(@publication.forum) %>
              <%= form_for subscription, method: :delete do |f| %>
              <%= f.hidden_field :forum_id, value: @publication.forum.id  %>
              <%= f.hidden_field :user_id, value: current_user.id  %>
              <%= f.hidden_field :publication_id, value: @publication.id  %>
              <%= f.submit 'Unsubscribe', class: 'btn btn-warning' %>
              <% end %>
            <% else %>
              <%= form_for subscription do |f| %>
              <%= f.hidden_field :forum_id, value: @publication.forum.id  %>
              <%= f.hidden_field :user_id, value: current_user.id  %>
              <%= f.hidden_field :publication_id, value: @publication.id  %>
              <%= f.submit 'Subscribe', class: 'btn btn-warning' %>
              <% end  %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="sidebar-container">
        <div class="sidebar-topbar"></div>
        <div class="sidebar-content">
          <h3>Other Publications</h3>
          <% @publication.forum.publications.each do |publication| %>
            <% if publication != @publication %>
              <%= link_to publication.title, publication %><br>

            <% end %>
          <% end %>
        </div>
      </div>
      <div class="sidebar-container">
        <div class="sidebar-topbar"></div>
        <div class="sidebar-content">
          <h3>Moderators</h3>
          <% @publication.forum.moderators.each do |moderator| %>
              <% if moderator.approved? %>
                <%= link_to moderator.user.userName, moderator.user %><br>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% else %>

<div class="row publication-meta">
    <p>
      Created by
      <%= link_to @publication.user.userName, @publication.user %>
      <% hours = (((Time.zone.now - @publication.created_at) / 3600).to_i) %>
      <% if  hours.zero? %>
      just now
      <% elsif  hours < 24 %>
      <%= hours %> hours ago
      <% else %>
      <%= (hours / 24).to_i%> days ago
      <% end %>
    </p>
</div>
<div class="row">

  <div class="col-xs-9">
    <div class="row">
      <div class="col-xs-1 publication-score">
        <p>
          <strong><%=@publication.votos%></strong>
        </p>
      </div>
      <div class="col-xs-11">
        <h1 id="publication-title">
          <strong><%= @publication.title %> </strong>
        </h1>
        <p style="font-size:110%;">
          <% if @publication.content_type == 'link' %>
            <a href="http://<%= @publication.content %>"><%= @publication.content %> </a>
          <% else %>
          <%= @publication.content %>
          <% end %>
        </p>
        <% if @publication.content_type == 'poll' %>
          <div class="poll-container">
            <h3><%= @publication.poll.question %> </h3>
            <% @publication.poll.poll_options.each do |option| %>
            <% value = (option.votos*100/@publication.poll.total).to_i %>
            <div class="progress">
              <div class="progress-bar" style="width: <%=value %>%;" role="progressbar" aria-valuenow="<%= value %>" aria-valuemin="0" aria-valuemax="100">
                <span><%= option.text %></span>
                <span class="percent"><%= value %>% </span>
              </div>
            </div>
            <% end %>
          <% end %>
          </div>
          <% unless @publication.image.nil? %>
          <img src="<%= @publication.image %> " alt="">
          <% end %>
        </div>
      <div class="row">
        <div class="col-xs-12">
        <h3>Comment Section</h3>
        <ul class="comment-list">
          <%= render partial: 'comments/comment', collection: @publication.comments.order(:created_at) %>
        </ul>
        <%= link_to 'Back', @publication.forum %>
        </div>
      </div>

  </div>

  <div class="col-xs-3 publication-sidebar">
    <div class="sidebar-container">
      <div class="sidebar-topbar"></div>
        <div class="sidebar-content">
          <h3>
            <%= link_to @publication.forum.title, @publication.forum %>
          </h3>
          <p><strong><%= @publication.forum.subscriptors %> Subscribers</strong> </p>
          <p><%= @publication.forum.description %> </p>
          <% if  user_signed_in? %>
            <% current = Subscription.where(forum: @publication.forum, user: current_user).take %>
            <% subscription = current.nil? ? Subscription.new : current %>
            <% if current_user.forums.include?(@publication.forum) %>
              <%= form_for subscription, method: :delete do |f| %>
              <%= f.hidden_field :forum_id, value: @publication.forum.id  %>
              <%= f.hidden_field :user_id, value: current_user.id  %>
              <%= f.submit 'Unsubscribe', class: 'btn btn-warning' %>
              <% end %>
            <% else %>
              <%= form_for subscription do |f| %>
              <%= f.hidden_field :forum_id, value: @publication.forum.id  %>
              <%= f.hidden_field :user_id, value: current_user.id  %>
              <%= f.submit 'Subscribe', class: 'btn btn-warning' %>
              <% end  %>
            <% end %>
          <% end %>
        </div>
    </div>
      <div class="sidebar-container">
        <div class="sidebar-topbar"></div>
        <div class="sidebar-content">
          <h3>Other Publications</h3>
          <% @publication.forum.publications.each do |publication| %>
            <% if publication != @publication %>
              <%= link_to publication.title, publication %><br>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="sidebar-container">
        <div class="sidebar-topbar"></div>
        <div class="sidebar-content">
          <h3>Moderators</h3>
          <% @publication.forum.moderators.each do |moderator| %>
              <% if moderator.approved? %>
                <%= link_to moderator.user.userName, moderator.user %><br>
              <% end %>

          <% end %>
        </div>
      </div>
  </div>

</div>
<% end %>

<script type="text/javascript">
$(document).ready(()=>{
  $('.reply-link').click(function(){
    const id = this.id;
    $('.reply-form').each(function(index,element){
      $(element).addClass('hide')
      $(element).removeClass('show')
    })
    $(`#comment-${id}`).addClass('show')
    $(`#comment-${id}`).removeClass('hide')

  })
})

</script>