config/routes.rb
Rails.application.routes.draw do
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # vote comments
  #  resources :vote_comments

  # vote publications
  post 'votes', to: 'votes#add_vote'
  post 'vote_comments', to: 'vote_comments#add_vote', as: 'add_comment_vote'

  # moderators
  post 'moderate/request', to: 'requests#apply'
  patch 'moderate/request/:id', to: 'requests#accept'
  delete 'moderate/request/:id', to: 'requests#reject'
  get 'moderate/request', to: 'requests#show', as: 'requests'
  delete 'moderate', to: 'requests#resign'

  # resources
  resources :publications
  resources :comments
  resources :subscriptions
  resources :favorites
  resources :forums

  # polls
  post 'poll', to: 'publications#poll_vote', as: 'poll_vote'

  # users
  resources :users
  post '/upload/:id', to: 'users#upload'

  # forums
  get '/forums/:id/new_publication/text', to: 'forums#new_publication', as: 'new_publication_text'
  get '/forums/:id/new_publication/link', to: 'forums#new_publication_link', as: 'new_publication_link'
  get '/forums/:id/new_publication/image', to: 'forums#new_publication_image', as: 'new_publication_image'
  post '/forums/:id/new_publication/image', to: 'forums#image_upload', as: 'image_upload'
  get '/forums/:id/new_publication/poll', to: 'forums#new_publication_poll', as: 'new_publication_poll'
  post '/forums/:id/new_publication/poll', to: 'forums#create_poll', as: 'create_poll'
  post '/forums/:id/new_publication/link', to: 'forums#create_link', as: 'create_link'

  # search
  get '/home/search/forums', to: 'home#search_forum', as: 'search_forum'
  get '/home/search/publications', to: 'home#search_publication', as: 'search_publication'
  get '/home/search/users', to: 'home#search_user', as: 'search_user'

  #  top
  get '/home/top_forums', to: 'home#top_forums', as: 'top_forums'
  get '/home/top/publications', to: 'home#top_publications', as: 'top_publications'
  get '/home/top/users', to: 'home#top_users', as: 'top_users'
  get '/home/top/subscribed', to: 'home#top_subscribed', as: 'top_subscribed'

  # home and root
  get 'welcome/index'
  root 'welcome#index'
  get '/home', to: 'home#index', as: :home

  # dashboard
  get '/stats', to: 'statistics#index', as: '/stats'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :publications, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :vote_comments, dependent: :destroy
  has_many :moderators, dependent: :destroy
  has_many :moderated_forums, through: :moderators, source: :forum
  has_many :forums, through: :subscriptions
  has_many :favorites, dependent: :destroy
  has_many :favorite_publications, through: :favorites, source: :publication
  has_many :poll_vote, dependent: :destroy

  before_create :default_role
  before_create :default_reputation
  before_create :default_facebook_registered

  validates :userName, uniqueness: true

  def self.search(search)
    where('userName ILIKE ? OR lastName ILIKE ? OR firstName ILIKE ?',
          "%#{search}%", "%#{search}%", "%#{search}%")
  end

  def default_role
    self.role ||= 2
  end

  def default_facebook_registered
    self.facebook_registered = 0 unless facebook_registered == 1
  end

  def accepted(forum_id)
    moderators.each do |m|
      return m.approved if m.forum_id == forum_id
    end
    false
  end

  def default_reputation
    self.reputation ||= 0
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data']) && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.userName = auth.info.name.downcase.tr(' ', '.') # assuming the user model has a name
      user.firstName = auth.info.name.match(' ').pre_match   # assuming the user model has a name
      user.lastName = auth.info.name.match(' ').post_match   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      user.facebook_registered = 1
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
  
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation, :remember_me, :avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    #if current_user.default_facebook_registered == 1  # registered with facebook
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :remember_me, :avatar])
    #end
    #if current_user.default_facebook_registered == 0
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :remember_me, :avatar])
    #end
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  # def user_params
  #   params.require(:user).permit(:userName, :firstName, :lastName, :role, :avatar)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, :userName, :firstName, :lastName, :role, :avatar)
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy upload]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @publications = @user.publications.order(:id)
    @subscriptions = @user.subscriptions.order(:id)
    moderating_forums = []
    @user.moderated_forums.order(:id).each do |forum|
      moderating_forums.push(forum) if @user.accepted(forum.id)
    end
    @moderating = moderating_forums
    requests_forums = []
    @user.moderated_forums.order(:id).each do |forum|
      requests_forums.push(forum) unless @user.accepted(forum.id)
    end
    @requests = requests_forums
    @starred = @user.favorite_publications.order(:id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html do
          redirect_to @user, notice: 'User was successfully created.'
        end
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html do
          redirect_to @user, notice: 'User was successfully updated.'
        end
        format.json do
          render :show, status: :ok, location: @user
        end
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html do
        redirect_to users_url, notice: 'User was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def upload
    uploaded_io = params[:picture]
    path = uploaded_io.tempfile.path
    save_screenshot_to_s3(path, 'folder', 1)
    redirect_to @user
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:userName, :firstName, :lastName, :role, :avatar, :picture)
  end

  def save_screenshot_to_s3(image_location, folder_name, _user_id)
    s3 = Aws::S3::Resource.new(region: 'sa-east-1')
    bucket_name = 'slash-bucket'
    key = folder_name.to_s + '/' + File.basename(image_location)
    object = s3.bucket(bucket_name).object(key)
    object.upload_file(image_location)
    @user.image = object.public_url.to_s
    @user.save
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :userName %>
    <%= form.text_field :userName, id: :user_userName %>
  </div>

  <div class="field">
    <%= form.label :firstName %>
    <%= form.text_field :firstName, id: :user_firstName %>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName, id: :user_lastName %>
  </div>

  <% if user_signed_in? %>
  <% if current_user.role.zero? %>
  <div class="field">
    <%= form.label :role %>
    <%= form.number_field :role, id: :user_role %>
  </div>
  <% end %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if user_signed_in? && (current_user == @user || current_user.role.zero?) %>

<h1>Edit User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |

<% else %>

<h2><strong> We're Sorry! </strong></h2>
<p style="font-size:20px"> You don't have permission to access this page. </p>

<% end %>

<%= link_to 'Back to Home', :home %>

app/views/users/index.html.erb
<% if user_signed_in? && current_user.role.zero? %>

<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Username</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.order(:id).each do |user| %>
      <tr>
        <td><%= link_to user.id, user %></td>
        <td><%= link_to user.userName, user %></td>
        <td><%= link_to user.firstName, user %></td>
        <td><%= link_to user.lastName, user %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tbody>
</table>

<br>

<%-# <%= link_to 'New User', new_user_path %>

<% else %>

<h2><strong> We're Sorry! </strong></h2>
<p style="font-size:20px"> You don't have permission to access this page. </p>

<% end %>

<%= link_to 'Back to Home', :home %>

app/views/users/new.html.erb
<% if user_signed_in? && current_user.role.zero? %>

<h1>New User</h1>

<%= render 'form', user: @user %>

<% else %>

<h2><strong> We're Sorry! </strong></h2>
<p style="font-size:20px"> You don't have permission to access this page. </p>

<% end %>

<%= link_to 'Back to Home', :home %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<div class="row top">
  <div class="col-xs-2">
    <% if @user.image %>
    <div class="profile-pic" style="background-image: url(<%= @user.image %>)">
    </div>
    <% else %>
    <div class="profile-pic">
    </div>
    <% end %>
    <br>
    <% if @user == current_user %>
      <%= form_tag("/upload/#{@user.id}", multipart: true) do %>
        <%= file_field_tag :picture, required: true %>
        <%= submit_tag 'Submit' %>
      <% end %>
    <% end %>
  </div>
  <div class="col-xs-8">
    <h1>
      <% pos = @user.reputation>=0 %>
      <span class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= @user.reputation%>)</span>
      <span><strong><%= @user.userName %></strong></span>

      <% if user_signed_in? && current_user == @user %>
      -
      <%= @user.firstName %>
      <%= @user.lastName %>
      <% end %>

      <% if @user.role.zero? %>
      <i style="font-size:20px">(admin)</i>
      <% end %>
    </h1>
    <span style="font-size:20px;color:#888">
      <strong style="color:#555"><%= @user.publications.count %></strong> Publications &nbsp;&nbsp;
      <strong style="color:#555"><%= @user.comments.count %></strong> Comments &nbsp;&nbsp;
      <strong style="color:#555"><%= @user.votes.count + @user.vote_comments.count %></strong> Votes
    </span>
  </div>
  <div class="col-xs-2"></div>
</div>

<hr>

<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'Publications')" id="defaultOpen">Publications</button>
  <button class="tablinks" onclick="openTab(event, 'Subscriptions')">Subscriptions</button>
  <button class="tablinks" onclick="openTab(event, 'Moderating Forums')">Moderating Forums</button>
  <button class="tablinks" onclick="openTab(event, 'Moderating Requests')">Moderating Requests</button>
  <button class="tablinks" onclick="openTab(event, 'Starred')">Starred</button>
</div>

<div id="Publications" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">&times</span>

  <div class="row top">
    <br>
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
    <% @publications.each do | publication | %>
      <div class="top-results">
        <div class="search-result well">
          <h4><%= publication.id %>. <%= link_to publication.title, publication %></h4>
          <% if publication.votos.nil? %>
            <% publication.votos = 0 %>
          <% end %>
          <% pos = publication.votos >= 0 %>
          <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= publication.votos%>)</h4>
          <% if publication.content.present? %>
          <h4>| <%= truncate(publication.try(:content), length:50, separator: ' ') %></h4>
          <% end %>
        </div>
      </div>
      <% end %>
      <% if @user.publications.size == 0 %>
        <center><em> The user has no publications. </em></center>
      <% end %>
    </div>

    <div class="col-xs-2"></div>
  </div>

</div>

<div id="Subscriptions" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">&times</span>

  <div class="row top">
    <br>
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
    <% @subscriptions.each do | subscription | %>
      <div class="top-results">
        <div class="search-result well">
          <h4><%= subscription.forum.id %>. <%= link_to subscription.forum.title, subscription.forum %></h4>
          <% pos = subscription.forum.votos>=0 %>
          <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= subscription.forum.votos%>)</h4>
          <h4>| <%= truncate(subscription.forum.try(:description), length:50, separator: ' ') %></h4>
        </div>
      </div>
      <% end %>
      <% if @subscriptions.size == 0 %>
        <center><em> The user has no subscriptions. </em></center>
      <% end %>
    </div>

    <div class="col-xs-2"></div>
  </div>

</div>

<div id="Moderating Forums" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">&times</span>

  <div class="row top">
    <br>
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
    <% @moderating.each do | forum | %>
      <div class="top-results">
        <div class="search-result well">
          <h4><%= forum.id %>. <%= link_to forum.title, forum %></h4>
          <% pos = forum.votos>=0 %>
          <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= forum.votos%>)</h4>
          <h4>| <%= truncate(forum.try(:description), length:50, separator: ' ') %></h4>
        </div>
      </div>
      <% end %>
      <% if @moderating.size == 0 %>
        <center><em> The user doesn't moderate any forums. </em></center>
      <% end %>
    </div>

    <div class="col-xs-2"></div>
  </div>

</div>

<div id="Moderating Requests" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">&times</span>

  <div class="row top">
    <br>
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
    <% @requests.each do | forum | %>
      <div class="top-results">
        <div class="search-result well">
          <h4><%= forum.id %>. <%= link_to forum.title, forum %></h4>
          <% pos = forum.votos>=0 %>
          <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= forum.votos%>)</h4>
          <h4>| <%= truncate(forum.try(:description), length:50, separator: ' ') %></h4>
        </div>
      </div>
      <% end %>
      <% if @requests.size == 0 %>
        <center><em> The user haven't requested to moderate any new forums. </em></center>
      <% end %>
    </div>

    <div class="col-xs-2"></div>
  </div>
</div>

<div id="Starred" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">&times</span>

  <div class="row top">
    <br>
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
    <% @starred.each do | publication | %>
      <div class="top-results">
        <div class="search-result well">
          <h4><%= publication.id %>. <%= link_to publication.title, publication %></h4>
          <% if publication.votos.nil? %>
            <% publication.votos = 0 %>
          <% end %>
          <% pos = publication.votos >= 0 %>
          <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= publication.votos%>)</h4>
          <h4>| <%= truncate(publication.try(:content), length:50, separator: ' ') %></h4>
        </div>
      </div>
      <% end %>
      <% if @starred.size == 0 %>
        <center><em> The user has no starred publications. </em></center>
      <% end %>
    </div>

    <div class="col-xs-2"></div>
  </div>

</div>

<%= link_to 'Back to Home', :home %>

<script>
function openTab(evt, tabName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>