config/routes.rb
Rails.application.routes.draw do
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # vote comments
  #  resources :vote_comments

  # vote publications
  post 'votes', to: 'votes#add_vote'
  post 'vote_comments', to: 'vote_comments#add_vote', as: 'add_comment_vote'

  # moderators
  post 'moderate/request', to: 'requests#apply'
  patch 'moderate/request/:id', to: 'requests#accept'
  delete 'moderate/request/:id', to: 'requests#reject'
  get 'moderate/request', to: 'requests#show', as: 'requests'
  delete 'moderate', to: 'requests#resign'

  # resources
  resources :publications
  resources :comments
  resources :subscriptions
  resources :favorites
  resources :forums

  # polls
  post 'poll', to: 'publications#poll_vote', as: 'poll_vote'

  # users
  resources :users
  post '/upload/:id', to: 'users#upload'

  # forums
  get '/forums/:id/new_publication/text', to: 'forums#new_publication', as: 'new_publication_text'
  get '/forums/:id/new_publication/link', to: 'forums#new_publication_link', as: 'new_publication_link'
  get '/forums/:id/new_publication/image', to: 'forums#new_publication_image', as: 'new_publication_image'
  post '/forums/:id/new_publication/image', to: 'forums#image_upload', as: 'image_upload'
  get '/forums/:id/new_publication/poll', to: 'forums#new_publication_poll', as: 'new_publication_poll'
  post '/forums/:id/new_publication/poll', to: 'forums#create_poll', as: 'create_poll'
  post '/forums/:id/new_publication/link', to: 'forums#create_link', as: 'create_link'

  # search
  get '/home/search/forums', to: 'home#search_forum', as: 'search_forum'
  get '/home/search/publications', to: 'home#search_publication', as: 'search_publication'
  get '/home/search/users', to: 'home#search_user', as: 'search_user'

  #  top
  get '/home/top_forums', to: 'home#top_forums', as: 'top_forums'
  get '/home/top/publications', to: 'home#top_publications', as: 'top_publications'
  get '/home/top/users', to: 'home#top_users', as: 'top_users'
  get '/home/top/subscribed', to: 'home#top_subscribed', as: 'top_subscribed'

  # home and root
  get 'welcome/index'
  root 'welcome#index'
  get '/home', to: 'home#index', as: :home

  # dashboard
  get '/stats', to: 'statistics#index', as: '/stats'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# frozen_string_literal: true

require 'will_paginate'

class HomeController < ApplicationController
  def index
    @top_forums = Forum.order(:votos).reverse_order
    @top_publications = Publication.order(:votos).reverse_order
    @top_users = User.order(:reputation).reverse_order
    query = Subscription.select(:forum_id).group(:forum_id).count
    top3 = top query, 3
    @popular_forums = []
    top3.each do |data|
      forum = Forum.find(data[0])
      forum.subscriptors = data[1]
      @popular_forums << forum
    end
    @popular_forums.reverse!
  end

  def top_forums
    @top_forums = Forum.order(:votos).reverse_order.paginate(page: params[:page], per_page: 5)
  end

  def top_publications
    @top_publications = Publication.order(:votos).reverse_order.paginate(page: params[:page], per_page: 5)
  end

  def top_users
    @top_users = User.order(:reputation).reverse_order.paginate(page: params[:page], per_page: 5)
  end

  def top_subscribed
    query = Subscription.select(:forum_id).group(:forum_id).count
    top_n = top query, Forum.all.length
    pop_forums = []
    top_n.each do |data|
      forum = Forum.find(data[0])
      forum.subscriptors = data[1]
      pop_forums << forum
    end
    @popular_forums = pop_forums.reverse.paginate(page: params[:page], per_page: 5)
  end

  def search_forum
    @home = false
    forums = Forum.search(params[:search_forum]).order(:created_at)
    @forums = forums.reverse_order.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html do
        render 'search_forum'
      end
    end
  end

  def search_publication
    @home = false
    pubs = Publication.search(params[:search_publication]).order(:created_at)
    @publications = pubs.reverse_order.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html do
        render 'search_publication'
      end
    end
  end

  def search_user
    @home = false
    users = User.search(params[:search_user]).order(:created_at).reverse_order
    @users = users.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html do
        render 'search_user'
      end
    end
  end

  private

  def top(hash, number)
    top = hash.sort_by { |_key, value| value }
    return top[-number..-1] if top.length >= number
    top
  end
end

app/views/home/index.html.erb
<br>
<div class="row search">
  <div class="search-form well">
    <h1>Search Forums</h1>
    <%= form_tag(search_forum_path, :method => "get", id: "search-forum") do %>
    <%= text_field_tag :search_forum, params[:search_forum], placeholder: "Search Forums" %>
    <%= submit_tag "Search", name: nil, class: 'btn-primary' %>
    <% end %>
    <% unless @forums.nil?  && @users.nil? %>
      <% if user_signed_in? && current_user.role.zero? %>
        <%= link_to 'New Forum', new_forum_path %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row search">
  <div class="search-form well">
    <h1>Search Publications</h1>
    <%= form_tag(search_publication_path, :method => "get", id: "search-publication") do %>
    <%= text_field_tag :search_publication, params[:search_publication], placeholder: "Search Publication" %>
    <%= submit_tag "Search", name: nil, class: 'btn-primary' %>
    <% end %>
  </div>
</div>

<div class="row top">
  <div class="col-xs-6">
    <h2><%= link_to 'Top 3 Forums', top_forums_path%></h2>
    <% @top_forums.take(3).each do |forum| %>
      <div class=" top-results">
        <div class="search-result well">
          <h4><%= link_to forum.title, forum %></h4>
          <% pos = forum.votos>=0 %>
          <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= forum.votos%>)</h4>
          <h4>| <%= truncate(forum.try(:description), length:50, separator: ' ') %></h4>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-xs-6">
    <h2><%= link_to 'Top 3 Publications', top_publications_path%></h2>
    <% @top_publications.take(3).each do |publication| %>
      <div class=" top-results">
        <div class="search-result well">
          <h4><%= link_to publication.title, publication %></h4>
          <% if publication.votos.nil? %>
            <% publication.votos = 0 %>
          <% end %>
          <% pos = publication.votos >= 0 %>
          <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= publication.votos%>)</h4>
          <h4>| <%= truncate(publication.try(:content), length:50, separator: ' ') %></h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row top">
  <div class="col-xs-6">
    <h2><%= link_to 'Top 3 Users', top_users_path%></h2>
    <% @top_users.take(3).each do |user| %>
      <div class=" top-results">
        <div class="search-result well">
          <h4><%= link_to user.userName, user %></h4>
          <% pos = user.reputation >=0 %>
          <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= user.reputation %>)</h4>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-xs-6">
    <h2><%= link_to 'Top 3 Subscribed Forums', top_subscribed_path%></h2>
    <% @popular_forums.each do |forum| %>
      <div class=" top-results">
        <div class="search-result well">
          <h4><%= link_to forum.title, forum %></h4>
          <% pos = forum.votos>=0 %>
          <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= forum.votos%>)</h4>
          <h4> |  <%= forum.subscriptors %> Subscriptions</h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/search_forum.html.erb
<div class="row search">
  <br>
  <div class="search-form well">
    <h1>Search Forums</h1>
    <%= form_tag(search_forum_path, :method => "get", id: "search-forum") do %>
    <%= text_field_tag :search_forum, params[:search_forum], placeholder: "Search Forums" %>
    <%= submit_tag "Search", name: nil, class: 'btn-primary' %>
    <% end %>
    <h3><%= link_to 'Top Forums', top_forums_path%></h3>
    <% unless @forums.nil?  && @users.nil? %>
      <% if user_signed_in? && current_user.role.zero? %>
        <h3><%= link_to 'New Forum', new_forum_path %></h3>
      <% end %>
    <% end %>
  </div>
</div>

<% @forums.each do |forum| %>
<div class="search">
  <div class="search-result well">
    <h3><%= link_to forum.title, forum %></h3>
    <% pos = forum.votos>=0 %>
    <h3 class="votes-<%= pos ? 'green' : 'red' %> ">  (<%= pos ? '+': ''  %><%= forum.votos%>)</h3>
    <h3>| <%= forum.description %></h3>
  </div>
</div>
<% end %>



<center>
<div class="digg_pagination">
<%= will_paginate @forums %>
</div>
</center>

app/views/home/search_publication.html.erb
<div class="row search">
  <br>
  <div class="search-form well">
    <h1>Search Publications</h1>
    <%= form_tag(search_publication_path, :method => "get", id: "search-publication") do %>
    <%= text_field_tag :search_publication, params[:search_publication], placeholder: "Search Publication" %>
    <%= submit_tag "Search", name: nil, class: 'btn-primary' %>
    <% end %>
    <h3><%= link_to 'Top Publications', top_publications_path%></h3>

  </div>
</div>

<% @publications.each do |publication| %>
  <div class="row search">
    <div class="search-result well">
      <h3> <%= link_to publication.forum.title, publication.forum %>:  </h3>
      <h3><%= link_to publication.title, publication %></h3>
      <% pos = publication.votos>=0 %>
      <h3 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= publication.votos%>)</h3>
      <h3> - By <%= link_to publication.user.userName, publication.user  %></h3>
    </div>
  </div>
<% end %>  

<center>
<div class="digg_pagination">
<%= will_paginate @publications %>
</div>
</center>

app/views/home/search_user.html.erb
<div class="row search">
  <div class="search-form well">
    <h1>Search Users</h1>
    <%= form_tag(search_user_path, :method => "get", id: "search-user") do %>
    <%= text_field_tag :search_user, params[:search_user], placeholder: "Search User" %>
    <%= submit_tag "Search", name: nil, class: 'btn-primary' %>
    <% end %>
  </div>
</div>

<% @users.each do |user| %>
  <div class="row search">
    <div class="search-result well">
      <h3><%= link_to user.userName, user %></h3>
      <% pos = user.reputation>=0 %>
      <h3 class="reputation-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': '-'  %> <%= user.reputation%>)</h3>
    </div>
  </div>
<% end %>

app/views/home/top_forums.html.erb
<div class="row top">
  <br>
  <h1 align="center">Top Forums</h1>
  <br>
  <% @top_forums.each do |forum| %>
    <div class=" top-results">
      <div class="search-result well">
        <h4><%= link_to forum.title, forum %></h4>
        <% pos = forum.votos>=0 %>
        <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= forum.votos%>)</h4>
        <h4>| <%= forum.description %></h4>
      </div>
    </div>
  <% end %>
</div>


<center>
<div class="digg_pagination">
<%= will_paginate @top_forums %>
</div>
</center>

app/views/home/top_publications.html.erb
<div class="row top">
  <br>
  <h1 align="center">Top Publications</h1>
  <br>
  <% @top_publications.each do |publication| %>
    <div class=" top-results">
      <div class="search-result well">
        <h4><%= link_to publication.title, publication %></h4>
        <% pos = publication.votos>=0 %>
        <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= publication.votos%>)</h4>
        <h4>| <%= publication.content %></h4>
      </div>
    </div>
  <% end %>
</div>

<center>
<div class="digg_pagination">
<%= will_paginate @top_publications %>
</div>
</center>

app/views/home/top_subscribed.html.erb
<div class="row top">
  <br>
  <h2>Most Subscribed Forums</h2>
  <br>
  <% @popular_forums.each do |forum| %>
    <div class=" top-results">
      <div class="search-result well">
        <h4><%= link_to forum.title, forum %></h4>
        <% pos = forum.votos>=0 %>
        <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= forum.votos%>)</h4>
        <h4>| <%= forum.description %></h4>
        <h4>| <%= forum.subscriptors %></h4>
      </div>
    </div>
  <% end %>
</div>


<center>
<div class="digg_pagination">
  <%= will_paginate @popular_forums %>
</div>
</center>

app/views/home/top_users.html.erb
<div class="row top">
  <br>
  <h2>Top Users</h2>
  <br>
  <% @top_users.each do |user| %>
    <div class=" top-results">
      <div class="search-result well">
        <h4><%= link_to user.userName, user %></h4>
        <% pos = user.reputation >=0 %>
        <h4 class="votes-<%= pos ? 'green' : 'red' %> "> (<%= pos ? '+': ''  %> <%= user.reputation %>)</h4>
      </div>
    </div>
  <% end %>
</div>


<center>
<div class="digg_pagination">
<%= will_paginate @top_users %>
</div>
</center>